openapi: 3.0.0
info:
  title: Library Management System API
  description: This is the API Collection of the Library Management System.
  version: 0.1.9

tags:
  - name: genres
    description: API Collection for Genres

paths:
  /genres/{offset}/{limit}/{status}:
    get:
      tags:
        - genres
      summary: Returns a list of genres.
      description: This API endpoint returns all the genres.
      parameters:
        - name: offset
          in: path
          required: true
          schema:
            type: integer

        - name: limit
          in: path
          required: true
          schema:
            type: integer
        - name: status
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Pagination:
      type: object
      properties:
        offset:
          type: integer
        limit:
          type: integer
        status:
          type: string